---
title: "R Notebook"
output: html_notebook
---

1. Vectores y matrices
```{r}
#1.1

student_1 <- c( 50.4, 62.3, 92.1, 77.6, TRUE )
student_2 <- c( 41.7, 87.9, 75.3, 72.4, FALSE )
student_3 <- c( 30.3, 67.8, 69.3, 71.2, FALSE )
student_4 <- c( 65.4, 85.1, 92.3, 96.8, TRUE )
student_5 <- c( 70.4, 88.2, 95.2, 90.7, TRUE )

#1.2
students_vector <- c(student_1, student_2, student_3, student_4, student_5)
students_vector

#1.3
students_matrix <- matrix(students_vector, byrow = TRUE, nrow = 5)
students_matrix
```

2. Nombrado de una matriz
```{r}
#2.1
name_students <- c( "Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones", "Tom Hill" )
name_courses_legal_age <- c( "TIC", "Accounting", "Psychology", "Ethics", "Legal_age" )

#2.2
rownames(students_matrix) <- name_students
colnames(students_matrix) <- name_courses_legal_age
students_matrix
```

3. rowSums, cbind
```{r}
#3.1
total_grade_student <- rowSums(students_matrix[,1:4])
total_grade_student

#3.2
result_students <- cbind(students_matrix, total_grade_student)
result_students
```

4. Seleccionando elementos de una matriz
```{r}
#4.1
selected_elements <- result_students[c(1,3,5), c(2,4)]
selected_elements
```

5. Data frames
```{r}
#5.1
students_grades_df <- data.frame(result_students)
students_grades_df

#5.2
subset(students_grades_df, subset = Accounting > 80 & Legal_age == TRUE)
```

6. Funciones, Condicionales y Bucles
```{r}
#6.1
students_projection <- function(matrixP, notConsiderCol){
  for (rowNumber in 1:nrow(matrixP) ) {
    for (colNumber in 1:ncol(matrixP)) {
      if (!(colNumber %in% notConsiderCol)) {
        print(paste("El valor en la fila No. ", rowNumber, " y columna No. ", colNumber, " es: ", matrixP[rowNumber, colNumber]))
        
        
#6.2 - Start
        #6.2.1
        if (matrixP[rowNumber, colNumber] <= 45) {
          print("Student at risk")
        }
        #6.2.2
        else if(matrixP[rowNumber, colNumber] > 45 & matrixP[rowNumber, colNumber] < 61){
          print("Student may be approved")
        }
        #6.2.3
        else if(matrixP[rowNumber, colNumber] >= 61){
          print("Student approved")
        }
#6.2- End

      }
    }
  }
}


#6.3
result_students
#students_projection(result_students, c(5))
students_projection(result_students, c(5,6))
```
